### ISSUE TITLE
dfoptim seems required, not suggested

### ISSUE THREAD

**Issue by justinmcgrath** [eloch216/PhotoGEA#49]
dfoptim is used in `fit_c3_aci`, which appears to be a core function of the package, but dfoptim is only in the suggested packaged.

**Comment by eloch216** [comment]
I previously tried putting `dfoptim` into `Imports` or `Depends`, but then I get this `NOTE` from `R CMD check`:

```
checking dependencies in R code ... NOTE
Namespace in Imports field not imported from: 'dfoptim'
```

(Or something similar if `dfoptim` is in `Depends`.)

On the other, `R CMD check` doesn't have a problem with `dfoptim` being in `Suggests`. I guess maybe `dfoptim::nmkb` doesn't get imported until the function is actually called because it's only part of a default argument value. Maybe one way to address this would be to make a new function in the namespace (`default_optimizer`) that's defined to be the current default value of `OPTIM_FUN`:

```
default_optimizer <- function() {
    function(guess, fun, lower, upper) {
        dfoptim::nmkb(guess, fun, lower, upper, control = list(
            tol = 1e-7,
            maxfeval = 2000,
            restarts.max = 10
    ))
}
```

Then the default value of `OPTIM_FUN` could be changed to `default_optimizer`.

I could change this in the next release. I'm trying to be "professional" about updating this package. (Getting myself used to it since we will start doing this with BioCro.) There is a development branch called `unreleased` which gets merged into `main` from time to time. When that happens, I increment the package version number and make a release. Right now, I'm not exactly following the `major.minor.bug` format; I'm waiting until I'm able to document all the functions and address any other `NOTES` from `R CMD check`, then I will make version `1.0.0`.
